/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#FF7A00",
        "on-primary-fixed": "#331600",
        "on-tertiary-container": "#3d617f",
        "primary": "#FF7A00",
        "inverse-on-surface": "#f0f0f3",
        "on-surface": "#1a1c1e",
        "on-primary-fixed-variant": "#7A3D00",
        "on-primary": "#ffffff",
        "primary-fixed": "#FFDCC0",
        "secondary": "#476083",
        "surface-bright": "#f9f9fc",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#254a67",
        "error": "#ba1a1a",
        "surface-dim": "#dadadc",
        "tertiary": "#3e6280",
        "on-tertiary-fixed": "#001d32",
        "on-secondary-container": "#445d80",
        "on-error-container": "#93000a",
        "primary-container": "#FFE4D0",
        "surface-container": "#eeeef0",
        "on-background": "#1a1c1e",
        "surface-container-high": "#e8e8ea",
        "tertiary-fixed-dim": "#a7caee",
        "on-secondary-fixed": "#001c3a",
        "background": "#f9f9fc",
        "on-secondary": "#ffffff",
        "surface": "#f9f9fc",
        "surface-container-highest": "#e2e2e5",
        "on-secondary-fixed-variant": "#2f486a",
        "secondary-container": "#bdd6ff",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "outline": "#85736b",
        "tertiary-fixed": "#cde5ff",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#FFB688",
        "tertiary-container": "#b7dbff",
        "inverse-primary": "#FFB688",
        "inverse-surface": "#2f3133",
        "outline-variant": "#d8c2b9",
        "surface-variant": "#e2e2e5",
        "on-primary-container": "#FF7A00",
        "secondary-fixed": "#d4e3ff",
        "surface-container-low": "#f3f3f6",
        "on-surface-variant": "#53433a",
        "secondary-fixed-dim": "#afc8f0"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Lexend", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [],
}
